In [1]:
import numpy as np

In [2]:
my_list= [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [3]:
my_list

[1, 2, 3, 4, 5, 6]

In [4]:
np.array(my_list)


array([1, 2, 3, 4, 5, 6])

In [6]:
arr= np.array(my_list)

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(1)

array([1.])

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(10)

array([0.51954499, 0.39973688, 0.52814864, 0.15944777, 0.77230341,
       0.65093553, 0.33418843, 0.67636768, 0.71804858, 0.10602761])

In [31]:
np.random.rand(5,5)

array([[0.74680431, 0.65876078, 0.17761706, 0.52768788, 0.84685281],
       [0.61299873, 0.64019737, 0.80885324, 0.77287214, 0.48028809],
       [0.8408119 , 0.26067174, 0.82150306, 0.25543124, 0.96627818],
       [0.27589907, 0.23494486, 0.59837892, 0.3792948 , 0.11034562],
       [0.44166767, 0.38306362, 0.21058657, 0.55767749, 0.12122398]])

In [37]:
np.random.randint(1,1000,100)

array([331, 858, 274, 707, 997,  51, 707, 173, 660, 812, 333, 515, 791,
       587, 868, 727, 399, 499,  17, 135, 567, 130, 155, 195,  55, 536,
       519, 922, 270, 228, 165, 509,  89, 743,  26, 476, 998, 487, 953,
       714, 640, 837, 843, 467, 232, 882,  78, 744, 859,  17, 606, 893,
       920,  76, 606, 365, 181, 128, 787, 283, 626, 332, 264, 751, 889,
        45,  41, 937, 665, 423, 285, 922, 372, 609,  11, 198, 901, 630,
       368, 602, 815, 403,  12, 729,  80, 540, 665, 701, 503, 274, 217,
       287, 203, 438, 138, 971, 100, 957, 240, 226])

In [39]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([26,  5, 14, 17,  8,  2, 12,  8, 46, 23])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])